[ 2025-01-26 13:04:32,859:INFO:2638354798:Data downloaded from: https://github.com/Robin-star-lab/stroke_zip/raw/refs/heads/main/stroke_zip/healthcare-dataset-stroke-data.zip into: artifacts/data_ingestion/data.zip]
[ 2025-01-26 13:04:33,191:INFO:2638354798:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-26 13:23:13,342:INFO:1327809713:Data downloaded from: https://github.com/Robin-star-lab/stroke_zip/raw/refs/heads/main/stroke_zip/healthcare-dataset-stroke-data.zip into: artifacts/data_ingestion/data.zip]
[ 2025-01-26 13:23:13,657:INFO:1327809713:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-26 13:27:02,588:INFO:3999868275:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-26 13:28:52,035:INFO:1458254983:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-26 16:07:01,530:INFO:data_ingestion:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-26 16:07:01,541:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-26 19:38:35,884:INFO:data_ingestion:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-26 19:38:36,085:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-26 19:38:36,564:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-26 21:19:27,396:INFO:data_ingestion:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-26 21:19:27,396:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-26 21:19:27,667:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-27 07:39:15,919:INFO:data_ingestion:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-27 07:39:15,920:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-27 07:39:16,090:INFO:main:======Data Evaluation Stage======Successfully Completed.]
[ 2025-01-27 07:41:18,064:INFO:data_ingestion:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-27 07:41:18,064:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-27 07:41:18,124:INFO:main:======Data Evaluation Stage======Successfully Completed.]
[ 2025-01-27 07:41:18,690:INFO:main:======Data Transformation Stage======Successfully Completed.]
[ 2025-01-28 11:40:18,264:INFO:data_ingestion:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-28 11:40:18,275:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-28 11:40:18,457:INFO:main:======Data Evaluation Stage======Successfully Completed.]
[ 2025-01-28 11:40:20,821:INFO:main:======Data Transformation Stage======Successfully Completed.]
[ 2025-01-28 11:40:25,729:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[ 2025-01-28 11:40:26,252:INFO:main:======Model Training Stage======Successfully Completed.]
[ 2025-01-28 13:16:30,940:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 13:19:48,367:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 13:21:25,630:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 13:22:50,850:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 13:23:59,179:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 13:32:49,076:INFO:data_ingestion:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-28 13:32:49,077:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-28 13:32:49,168:INFO:main:======Data Evaluation Stage======Successfully Completed.]
[ 2025-01-28 13:32:50,818:INFO:main:======Data Transformation Stage======Successfully Completed.]
[ 2025-01-28 13:32:56,607:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[ 2025-01-28 13:32:56,840:INFO:main:======Model Training Stage======Successfully Completed.]
[ 2025-01-28 13:53:27,798:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 13:54:15,581:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 13:55:17,935:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 14:32:12,772:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 14:35:49,379:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 14:58:38,394:INFO:data_ingestion:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-28 14:58:38,396:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-28 14:58:38,608:INFO:main:======Data Evaluation Stage======Successfully Completed.]
[ 2025-01-28 14:58:40,602:INFO:main:======Data Transformation Stage======Successfully Completed.]
[ 2025-01-28 14:58:48,624:INFO:main:======Model Training Stage======Successfully Completed.]
[ 2025-01-28 14:58:48,873:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 14:58:51,006:INFO:main:======Model Evaluation Stage======Successfully Completed.]
[ 2025-01-28 17:05:16,408:INFO:data_ingestion:Extracted the zipfile: artifacts/data_ingestion/data.zip into: artifacts/data_ingestion]
[ 2025-01-28 17:05:16,424:INFO:main:======Data Ingestion Stage======Successfully Completed.]
[ 2025-01-28 17:05:16,740:INFO:main:======Data Evaluation Stage======Successfully Completed.]
[ 2025-01-28 17:05:18,715:INFO:main:======Data Transformation Stage======Successfully Completed.]
[ 2025-01-28 17:05:33,757:INFO:main:======Model Training Stage======Successfully Completed.]
[ 2025-01-28 17:05:34,063:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[ 2025-01-28 17:05:36,944:INFO:main:======Model Evaluation Stage======Successfully Completed.]
[ 2025-01-31 11:26:42,414:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.17.6.184:8080]
[ 2025-01-31 11:26:42,434:INFO:_internal:[33mPress CTRL+C to quit[0m]
[ 2025-01-31 11:26:59,054:INFO:_internal:127.0.0.1 - - [31/Jan/2025 11:26:59] "GET / HTTP/1.1" 200 -]
[ 2025-01-31 11:27:01,365:INFO:_internal:127.0.0.1 - - [31/Jan/2025 11:27:01] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[ 2025-01-31 11:27:19,679:ERROR:app:Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py", line 18, in predict
    age = int(request.form.get['age'])
              ~~~~~~~~~~~~~~~~^^^^^^^
TypeError: 'method' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py", line 38, in predict
    raise CustomException(e,sys)
Exceptions.CustomException: Error occured in python script no [C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py] line no [18] error message ['method' object is not subscriptable]
[ 2025-01-31 11:27:19,689:INFO:_internal:127.0.0.1 - - [31/Jan/2025 11:27:19] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[ 2025-01-31 11:35:43,079:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.17.6.184:8080]
[ 2025-01-31 11:35:43,080:INFO:_internal:[33mPress CTRL+C to quit[0m]
[ 2025-01-31 11:35:52,736:INFO:_internal:127.0.0.1 - - [31/Jan/2025 11:35:52] "GET / HTTP/1.1" 200 -]
[ 2025-01-31 11:36:03,825:ERROR:app:Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py", line 18, in predict
    age = int(request.form.get(['age']))
              ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py", line 38, in predict
    raise CustomException(e,sys)
Exceptions.CustomException: Error occured in python script no [C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py] line no [18] error message ['method' object is not subscriptable]
[ 2025-01-31 11:36:03,850:INFO:_internal:127.0.0.1 - - [31/Jan/2025 11:36:03] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[ 2025-01-31 14:25:08,460:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.17.3.22:8080]
[ 2025-01-31 14:25:08,474:INFO:_internal:[33mPress CTRL+C to quit[0m]
[ 2025-01-31 14:25:56,596:INFO:_internal:127.0.0.1 - - [31/Jan/2025 14:25:56] "GET / HTTP/1.1" 200 -]
[ 2025-01-31 14:25:59,675:INFO:_internal:127.0.0.1 - - [31/Jan/2025 14:25:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[ 2025-01-31 14:27:58,295:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.17.3.22:8080]
[ 2025-01-31 14:27:58,296:INFO:_internal:[33mPress CTRL+C to quit[0m]
[ 2025-01-31 14:28:17,069:INFO:_internal:127.0.0.1 - - [31/Jan/2025 14:28:17] "GET / HTTP/1.1" 200 -]
[ 2025-01-31 14:28:17,229:INFO:_internal:127.0.0.1 - - [31/Jan/2025 14:28:17] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[ 2025-01-31 14:29:47,284:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.17.3.22:8080]
[ 2025-01-31 14:29:47,285:INFO:_internal:[33mPress CTRL+C to quit[0m]
[ 2025-01-31 14:29:51,987:INFO:_internal:127.0.0.1 - - [31/Jan/2025 14:29:51] "GET / HTTP/1.1" 200 -]
[ 2025-01-31 14:30:13,756:ERROR:app:Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py", line 18, in predict
    age = int(request.form.get(['age']))
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\werkzeug\datastructures\structures.py", line 106, in get
    rv = self[key]
         ~~~~^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\werkzeug\datastructures\structures.py", line 234, in __getitem__
    if key in self:
       ^^^^^^^^^^^
TypeError: unhashable type: 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py", line 38, in predict
    raise CustomException(e,sys)
Exceptions.CustomException: Error occured in python script no [C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py] line no [18] error message [unhashable type: 'list']
[ 2025-01-31 14:30:13,768:INFO:_internal:127.0.0.1 - - [31/Jan/2025 14:30:13] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[ 2025-01-31 14:31:20,107:INFO:_internal:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.17.5.180:8080]
[ 2025-01-31 14:31:20,108:INFO:_internal:[33mPress CTRL+C to quit[0m]
[ 2025-01-31 14:31:26,843:INFO:_internal:127.0.0.1 - - [31/Jan/2025 14:31:26] "GET / HTTP/1.1" 200 -]
[ 2025-01-31 14:31:26,983:INFO:_internal:127.0.0.1 - - [31/Jan/2025 14:31:26] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[ 2025-01-31 14:31:42,807:ERROR:app:Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py", line 18, in predict
    age = int(request.form.get(['age']))
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\werkzeug\datastructures\structures.py", line 106, in get
    rv = self[key]
         ~~~~^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\werkzeug\datastructures\structures.py", line 234, in __getitem__
    if key in self:
       ^^^^^^^^^^^
TypeError: unhashable type: 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\stroke\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py", line 38, in predict
    raise CustomException(e,sys)
Exceptions.CustomException: Error occured in python script no [C:\Users\Robin Aluma\Desktop\Stroke_Detection\app.py] line no [18] error message [unhashable type: 'list']
[ 2025-01-31 14:31:42,816:INFO:_internal:127.0.0.1 - - [31/Jan/2025 14:31:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
